### PR TITLE
add CODEOWNERS

### PR DESCRIPTION
**Pull request by deitch**

### CODE REVIEW

**Review by milan-zededa — APPROVED** [review]

**Comment by deitch** [comment]
I am confused by the error, which is [here](https://github.com/lf-edge/eve-libs/actions/runs/5666220843/job/15352517076?pr=3#step:4:63). I can replicate it locally:

```bash
GOOS=linux go vet ./nettrace 
# github.com/lf-edge/eve-libs/nettrace
nettrace/nettrace.go:48:25: method WriteTo(w io.Writer) error should have signature WriteTo(io.Writer) (int64, error)
```

"should" have that signature? "should" by what measure? It doesn't look like it is implementing a particular `interface`, so why is it failing?

**Comment by milan-zededa** [comment]
@deitch That's strange indeed, it desperately wants us to follow the interface [WriterTo from the io package](https://pkg.go.dev/io#WriterTo). I will prepare that change in a separate PR to make go vet happy. For EVE it does not matter.

**Comment by deitch** [comment]
Yeah but why? There is no rule in go that says I cannot implement my own WriteTo; only if it implements that interface does it need to comply.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
