### PR TITLE
nettrace: fix go vet

### PR DESCRIPTION
**Pull request by christoph-zededa**
nettrace: fix go vet

### CODE REVIEW

**Comment by christoph-zededa** [comment]
`go vet` fails with: `./nettrace.go:48:25: method WriteTo(w io.Writer) error should have signature WriteTo(io.Writer) (int64, error)`

**Comment by rouming** [comment]
I do not think it is possible that max attempts reached but error list is empty. Please take a look, almost all 'continue' or 'break' code paths do the 'appendErorrList()'. There is only one place where error is not added is the following:
```
		newLastModified := resp.Header.Get("Last-Modified")
		if lastModified != "" && newLastModified != lastModified {
			// last modified changed, retry from the beginning
			lastModified = newLastModified
			forceRestart = true
			continue
		}
```

**Comment by christoph-zededa** [comment]
> I do not think it is possible that max attempts reached but error list is empty. Please take a look, almost all 'continue' or 'break' code paths do the 'appendErorrList()'. There is only one place where error is not added is the following:
> 
> ```
> 		newLastModified := resp.Header.Get("Last-Modified")
> 		if lastModified != "" && newLastModified != lastModified {
> 			// last modified changed, retry from the beginning
> 			lastModified = newLastModified
> 			forceRestart = true
> 			continue
> 		}
> ```

I removed that commit as you do https://github.com/lf-edge/eve-libs/pull/8/commits/9641fb06db980c384b4215e84dcac08c5c9bb598 instead

**Comment by christoph-zededa** [comment]
close because of https://github.com/lf-edge/eve-libs/pull/4/files#diff-e00aa0a07d55b694471e19e0e97cf6f4b73161f664b6c0e03d61e31051a62095R48

**Pull request closed without merging**
