### PR TITLE
Libs history

### PR DESCRIPTION
**Pull request by deitch**
Move libs over from eve. Includes yetus and updated README

### CODE REVIEW

**Comment by deitch** [comment]
Note that the DCO is because of very old commits that do not have signatures. It will need to be ignored.

**Comment by eriknordmark** [comment]
@deitch shouldn't we also have a GH workflow (or two) to build and run unittest basically running go build and go test in the subdirs?

**Comment by deitch** [comment]
Yeah, I can do that. No real "build", as none of these has a target binary, but close enough.

**Comment by deitch** [comment]
Added, the repo needs to be updated in "Settings" to take advantage of it.

**Review by eriknordmark — APPROVED** [review]
LGTM but I believe there has been one eve/libs PR merged since you started this PR. Can you check and add that one? Or do you want to do a separate PR with it?

From what I can tell the GH workflows should be enabled. I guess we'll find out once this has been merged.

**Comment by deitch** [comment]
> Can you check and add that one? Or do you want to do a separate PR with it?

Nah, let's get this right. I will redo this one with the latest commit from here.

**Comment by deitch** [comment]
OK, strange that this was closed, and will not let me reopen it. I will start a new PR.

**Comment by deitch** [comment]
Ah, it will let me now. Reopening.

**Comment by deitch** [comment]
Replaced with #2

**Pull request closed without merging**
